name: Terraform GCP Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
            workload_identity_provider: 'projects/1083821300508/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'  
            service_account: 'composer@dauntless-loop-499615-j7.iam.gserviceaccount.com'

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Format Check
        run: terraform -chdir=terraform fmt -check

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Destroy Composer Environment
        run: terraform -chdir=terraform destroy -auto-approve -target=google_composer_environment.customer_composer -var-file=terraform.tfvars
        continue-on-error: true

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -var-file=terraform.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve tfplan

      - name: Upload PySpark Job to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: scripts/pyspark_job.py
          destination: customer-etl-bucket/jobs
